# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/influence.base.ipynb.

# %% auto 0
__all__ = ['Influence']

# %% ../../nbs/api/influence.base.ipynb 1
from ..imports import *

# %% ../../nbs/api/influence.base.ipynb 2
class Influence:
    def __init__(
        self,
        func: Callable, # A black-box function to be explained
        train_dataset: Tuple[Array, Array], # Training dataset
        additional_func_args: Dict = None, # Additional arguments for the black-box function
    ): 
        self.func = func
        self.additional_func_args = additional_func_args
        self.train_ds = train_dataset

    def attribute(self, inputs: Array, **kwargs) -> Array:
        """Compute influence for given inputs"""
        raise NotImplementedError

