# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/linear_model.ipynb.

# %% ../nbs/api/linear_model.ipynb 3
from __future__ import annotations
from .imports import *

# %% auto 0
__all__ = ['BaseEstimator', 'Lasso', 'Ridge']

# %% ../nbs/api/linear_model.ipynb 6
class BaseEstimator:
    def __init__(self):
        ...

    def fit(self, X, y):
        ...

# %% ../nbs/api/linear_model.ipynb 8
class Lasso(LinearModel):
    def __init__(self, alpha: float = 1.0, **kwargs):
        super().__init__(**kwargs)
        self.alpha = alpha

    def fit(self, X: jnp.ndarray, y: jnp.ndarray, weights: jnp.ndarray = None, **kwargs) -> LinearModel:
        return super().fit(X, y, weights, reg_term=1, alpha=self.alpha, **kwargs)

# %% ../nbs/api/linear_model.ipynb 9
class Ridge(LinearModel):
    def __init__(self, alpha: float = 1.0, **kwargs):
        super().__init__(**kwargs)
        self.alpha = alpha

    def fit(self, X: jnp.ndarray, y: jnp.ndarray, weights: jnp.ndarray = None, **kwargs) -> LinearModel:
        return super().fit(X, y, weights, reg_term=2, alpha=self.alpha, **kwargs)
