# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/attr.lime.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/api/attr.lime.ipynb 3
from ..imports import *
from .base import *
from ..linear_model import Lasso, Ridge
